PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Content (
	id INTEGER PRIMARY KEY ASC,
	userDataID INTEGER,
	data INTEGER,

	FOREIGN KEY (userDataID) REFERENCES UserData(id)
);

CREATE TABLE IF NOT EXISTS UserData (
	id INTEGER PRIMARY KEY ASC,
	data VARCHAR(40) UNIQUE
);
